apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-prod-front-admision-ingress
  annotations:
       kubernetes.io/ingress.class: nginx
       cert-manager.io/cluster-issuer: letsencrypt
       nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  tls:
    - hosts:
      - prod.salud.achs.cl
      secretName: admision-web-cert
  rules:
  - host: prod.salud.achs.cl 
    http:
      paths:
      - path: /web-admision(/?.*)
        backend:
          serviceName: web-prod-front-admision-service
          servicePort: 80
      - path: /web-firmadigital(/?.*)
        backend:
          serviceName: web-prod-front-firmadigital-service
          servicePort: 80
      - path: /web-firmadigital-totem(/?.*)
        backend:
          serviceName: web-prod-front-firmadigital-totem-service
          servicePort: 80             
      - path: /web-digitalizador-documentos(/?.*)
        backend:
          serviceName: web-prod-front-digitalizaciondocumentos-service
          servicePort: 80   
      - path: /orquestador/(.*)
        backend:
          serviceName: api-prod-orquestador-service
          servicePort: 80
       