trigger:
  - none
  
variables:
  VmImageName: 'ubuntu-latest'
  ContainerRegistryName: 'crdesacontainer'
  DockerNamespace: '$(ContainerRegistryName).azurecr.io'
  DockerRepository: 'desa/Admision_Digital/ACHS-FR-Admision'
  ImageTag: '_$(Build.BuildId)'
  

stages:
  - stage: Deploy_DESA
    displayName: Deploy DESA
    jobs: 
      - job: buildJob
        displayName: Build and Publish
        pool:
          vmImage: $(VmImageName)
        variables:
          - group: Variables-CICD_IaC
          - name: RUTADIRECTORIOENVS
            value: envs
        steps:
        - script: |
            pwd
            ls -lha
        - task: Docker@2
          displayName: Build and Push Docker Image
          inputs:
            repository: $(DockerRepository)
            command: buildAndPush
            Dockerfile: ./Dockerfile
            containerRegistry: $(ContainerRegistryName)
            tags: $(ImageTag)
          env:
            ARM_SKIP_PROVIDER_REGISTRATION: true
            ARM_CLIENT_ID: $(ARM_CLIENT_ID_DESA)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET_DESA)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID_DESA)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            ARM_ACCESS_KEY: $(ARM_ACCESS_KEY_DESA)
            TF_VAR_arm_client_id: $(ARM_CLIENT_ID_DESA)
            TF_VAR_arm_client_secret: $(ARM_CLIENT_SECRET_DESA)
            TF_VAR_arm_tenant_id: $(ARM_TENANT_ID)