trigger:
  batch: true
  branches:
    include:
      - master
      - stage
      - release/*
      - develop
      - hotfix/*

variables:
  - group: VARIABLE-ENTORNO-ADMISIONDIGITAL

  - name: Repositorio
    value: "salud/admision-digital/front-admision"

  - name: ImageTag
    value: "_$(Build.BuildId)"  

pool:
  vmImage: $(vmImageName)

stages:
  - stage: INFO
    displayName: "Building"
    jobs:
      - deployment: Info
        displayName: "Info"
        environment: "Info"
      - job: Build
        displayName: "Info"
        steps:
          - script: |
              echo "TargetBranch" $(System.PullRequest.TargetBranch)
              echo "sourceBranch " $(System.pullRequest.sourceBranch)

  # DESA #
  - stage: Deploy_DESA
    displayName: "Building Desploy DESA"
    condition: |
      and(
        startsWith(variables['system.pullRequest.sourceBranch'], variables['sourceBranchDesa']),
        eq(variables['Build.Reason'], 'PullRequest')
      )
    jobs:
      - deployment: Deploy
        displayName: "Deploy DESA"
        environment: "Deploy_DESA"
      - job: Build
        displayName: "Deploy_DESA"
        steps:
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              containerRegistry: $(ContainerRegistryName)
              repository: $(Repositorio)
              command: build
              Dockerfile: ./Dockerfile
              tags: $(ImageTag)
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              containerRegistry: $(ContainerRegistryName)
              repository: $(Repositorio)
              command: push
              tags: $(ImageTag)
          - task: CmdLine@2
            displayName: Get secrets
            inputs:
              script: |
                sed -i "s?imagen?$(ContainerRegistryName).azurecr.io/$(Repositorio):$(ImageTag)?" /home/vsts/work/1/s/manifests/envs/desa/web-front-admision-deployment.yaml
                sed -i "s?azureID?$(azureAdDesarrollo)?" /home/vsts/work/1/s/manifests/envs/desa/web-front-admision-deployment.yaml
          - task: KubernetesManifest@0
            inputs:
              action: "deploy"
              kubernetesServiceConnection: "AKS-DESA-SALUD-NS-ADMISIONDIGITAL"
              namespace: "admisiondigital"
              manifests: |
                /home/vsts/work/1/s/manifests/envs/desa/web-front-admision-deployment.yaml
                /home/vsts/work/1/s/manifests/envs/desa/web-front-admision-service.yaml
                /home/vsts/work/1/s/manifests/envs/desa/web-front-admision-ingress.yaml
              containers: $(ContainerRegistryName).azurecr.io/$(Repositorio):$(ImageTag)
  # DESA #

  # QA #
  - stage: Deploy_QA
    displayName: "Building Deploy QA"
    condition: |
       and(
         startsWith(variables['system.pullRequest.sourceBranch'], variables['sourceBranchQa']),
         startsWith(variables['system.pullRequest.TargetBranch'], variables['TargetBranchQa']),
         eq(variables['Build.Reason'], 'PullRequest')
       )
    jobs:
      - deployment: Deploy
        displayName: "Deploy QA"
        environment: "Deploy_QA"
      - job: Build
        displayName: "Deploy QA"
        steps:
          - task: CmdLine@2
            displayName: Get secrets
            inputs:
              script: |
                sed -i "s?imagen?$(ContainerRegistryName).azurecr.io/$(Repositorio):$(TagFrontAdmision)?" /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-deployment.yaml
                sed -i "s?azureID?$(azureAdQa)?" /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-deployment.yaml
          - task: KubernetesManifest@0
            inputs:
              action: "deploy"
              kubernetesServiceConnection: "AKS-QA-SALUD-NS-ADMISIONDIGITAL"
              namespace: "admisiondigital"
              manifests: |
                /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-deployment.yaml
                /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-service.yaml
                /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-ingress.yaml
              containers: $(ContainerRegistryName).azurecr.io/$(Repositorio):$(TagFrontAdmision)          
   # HOTFIX #
  - stage: Deploy_QA_Hotfix
    displayName: "Building Desploy Qa Hotfix"
    condition: |
       and(
         startsWith(variables['system.pullRequest.sourceBranch'], variables['sourceBranchDeployQaHotfix']),
         startsWith(variables['system.pullRequest.TargetBranch'], variables['TargetBranchQa']),
         eq(variables['Build.Reason'], 'PullRequest')
       )
    jobs:
      - deployment: Deploy
        displayName: "Deploy QA Hotfix"
        environment: "Deploy_QA"
      - job: Build
        displayName: "Deploy QA Hotfix"
        steps:
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              containerRegistry: $(ContainerRegistryName)
              repository: $(Repositorio)
              command: build
              Dockerfile: ./Dockerfile
              tags: $(ImageTag)
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              containerRegistry: $(ContainerRegistryName)
              repository: $(Repositorio)
              command: push
              tags: $(ImageTag)
          - task: CmdLine@2
            displayName: Get secrets
            inputs:
              script: |
                sed -i "s?imagen?$(ContainerRegistryName).azurecr.io/$(Repositorio):$(ImageTag)?" /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-deployment.yaml
                sed -i "s?azureID?$(azureAdQa)?" /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-deployment.yaml
          - task: KubernetesManifest@0
            inputs:
              action: "deploy"
              kubernetesServiceConnection: "AKS-QA-SALUD-NS-ADMISIONDIGITAL"
              namespace: "admisiondigital"
              manifests: |
                /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-deployment.yaml
                /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-service.yaml
                /home/vsts/work/1/s/manifests/envs/qa/web-front-admision-ingress.yaml
              containers: $(ContainerRegistryName).azurecr.io/$(Repositorio):$(ImageTag)
  # HOTFIX #
  # QA #

  # STG #
  - stage: Deploy_STG
    displayName: "Building Deploy STG"
    condition: |
       and(
          startsWith(variables['system.pullRequest.sourceBranch'], variables['sourceBranchStg']),
          startsWith(variables['system.pullRequest.TargetBranch'], variables['TargetBranchStg']),
          eq(variables['Build.Reason'], 'PullRequest')
       )
    jobs:
      - deployment: Deploy
        displayName: "Deploy STG"
        environment: "Deploy_STG"
      - job: Build
        displayName: "Deploy STG"
        steps:
          - task: CmdLine@2
            displayName: Get secrets
            inputs:
              script: |
                sed -i "s?imagen?$(ContainerRegistryName).azurecr.io/$(Repositorio):$(TagFrontAdmision)?" /home/vsts/work/1/s/manifests/envs/stg/web-front-admision-deployment.yaml
                sed -i "s?azureID?$(azureAdStg)?" /home/vsts/work/1/s/manifests/envs/stg/web-front-admision-deployment.yaml
          - task: KubernetesManifest@0
            inputs:
              action: "deploy"
              kubernetesServiceConnection: "AKS-STG-SALUD-NS-ADMISIONDIGITAL"
              namespace: "admisiondigital"
              manifests: |
                /home/vsts/work/1/s/manifests/envs/stg/web-front-admision-deployment.yaml
                /home/vsts/work/1/s/manifests/envs/stg/web-front-admision-service.yaml
                /home/vsts/work/1/s/manifests/envs/stg/web-front-admision-ingress.yaml
              containers: $(ContainerRegistryName).azurecr.io/$(Repositorio):$(TagFrontAdmision)   
  # STG #

  # PROD #
  - stage: Deploy_PROD
    displayName: "Building Deploy PROD"
    condition: |
       and(
          startsWith(variables['system.pullRequest.sourceBranch'], variables['sourceBranchProd']),
          startsWith(variables['system.pullRequest.TargetBranch'], variables['TargetBranchProd']),
          eq(variables['Build.Reason'], 'PullRequest')
       )
    jobs:
      - deployment: Deploy
        displayName: "Deploy PROD"
        environment: "Deploy_PROD"
      - job: Build
        displayName: "Deploy PROD"
        steps:
          - task: CmdLine@2
            displayName: Get secrets
            inputs:
              script: |
                sed -i "s?imagen?$(ContainerRegistryName).azurecr.io/$(Repositorio):$(TagFrontAdmision)?" /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-deployment.yaml
                sed -i "s?azureID?$(azureAdProd)?" /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-deployment.yaml
          - task: KubernetesManifest@0
            inputs:
              action: "deploy"
              kubernetesServiceConnection: "AKS-PROD-SALUD-NS-ADMISIONDIGITAL"
              namespace: "admisiondigital"
              manifests: |
                /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-deployment.yaml
                /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-service.yaml
                /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-ingress.yaml
              containers: $(ContainerRegistryName).azurecr.io/$(Repositorio):$(TagFrontAdmision)   
  # HOTFIX #
  - stage: Deploy_PROD_Hotfix
    displayName: "Building Desploy PROD Hotfix"
    condition: |
       and(
         startsWith(variables['system.pullRequest.sourceBranch'], variables['sourceBranchDeployProdHotfix']),
         eq(variables['Build.Reason'], 'PullRequest')
       )
    jobs:
      - deployment: Deploy
        displayName: "Deploy PROD Hotfix"
        environment: "Deploy_PROD"
      - job: Build
        displayName: "Deploy PROD Hotfix"
        steps:
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              containerRegistry: $(ContainerRegistryName)
              repository: $(Repositorio)
              command: build
              Dockerfile: ./Dockerfile
              tags: $(ImageTag)
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              containerRegistry: $(ContainerRegistryName)
              repository: $(Repositorio)
              command: push
              tags: $(ImageTag)
          - task: CmdLine@2
            displayName: Get secrets
            inputs:
              script: |
                sed -i "s?imagen?$(ContainerRegistryName).azurecr.io/$(Repositorio):$(ImageTag)?" /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-deployment.yaml
                sed -i "s?azureID?$(azureAdProd)?" /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-deployment.yaml
          - task: KubernetesManifest@0
            inputs:
              action: "deploy"
              kubernetesServiceConnection: "AKS-PROD-SALUD-NS-ADMISIONDIGITAL"
              namespace: "admisiondigital"
              manifests: |
                /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-deployment.yaml
                /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-service.yaml
                /home/vsts/work/1/s/manifests/envs/prod/web-front-admision-ingress.yaml
              containers: $(ContainerRegistryName).azurecr.io/$(Repositorio):$(ImageTag)
  # HOTFIX #       
  # PROD #