// tuve que apuntar performance a trayecto para no tener que desplegar los otros repos
window.REACT_APP_ISAPRES="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/isapres/"
window.REACT_APP_AFP="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/afp/"
window.REACT_APP_NACIONALIDADES="https://desa.performance.40.121.134.234.nip.io/orquestador/api/datosPaciente/nacionalidades/"
window.REACT_APP_IDIOMAS="https://desa.performance.40.121.134.234.nip.io/orquestador/api/datosPaciente/idiomas/"
window.REACT_APP_PAISES="https://desa.performance.40.121.134.234.nip.io/orquestador/api/datosPaciente/paises/"
window.REACT_APP_CATEGORIA_OCUPACIONAL="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/categoriaOcupacional/"
window.REACT_APP_TIPO_CONTRATO="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/tipoContrato/"
window.REACT_APP_JORNADA_TRABAJO="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/jornadaTrabajo/"
window.REACT_APP_TIPO_REMUNERACIONES="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/tipoRemuneracion/"
window.REACT_APP_COMUNA="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/comunas"
window.REACT_APP_SUCURSALES="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/sucursales"
window.REACT_APP_CENTROSACHS="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/centros"
window.REACT_APP_PROFESION="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/profesiones"
window.REACT_APP_ALERTAS="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/alertas"
window.REACT_APP_RAZONSOCIAL="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/razonSocialByName?companyName="
window.REACT_APP_CENTER_USER="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/centrosUser"
window.REACT_APP_LOG="https://desa.performance.40.121.134.234.nip.io/orquestador/api/logs/"
window.REACT_APP_RAZON_SOCIAL_RUT="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/razonSocialByRut?rut="
window.REACT_APP_VALIDAR_DATA_EMPRESA="https://desa.performance.40.121.134.234.nip.io/orquestador/api/paciente/"
window.REACT_APP_VALIDAR_DATA_PACIENTE="https://desa.performance.40.121.134.234.nip.io/orquestador/api/paciente/getPaciente"
window.REACT_APP_INTEGRACION_SAP="https://desa.performance.40.121.134.234.nip.io/orquestador/api/sap/integracionsap"
window.REACT_APP_HOMOLOGACION="https://desa.performance.40.121.134.234.nip.io/orquestador/api/admisionista/getAliasSapByEmail"
window.REACT_APP_GEO_AUTOCOMPLETE="https://desa.performance.40.121.134.234.nip.io/orquestador/api/geo/autocompletarDirecciones"
window.REACT_APP_GEO_STATICMAP="https://desa.performance.40.121.134.234.nip.io/orquestador/api/geo/getMapaEstatico"
window.REACT_APP_GEO_LATLNG="https://desa.performance.40.121.134.234.nip.io/orquestador/api/geo/getLatLng"
window.REACT_APP_GEO_DIRECTION="https://desa.performance.40.121.134.234.nip.io/orquestador/api/geo/getDireccion"
window.REACT_APP_MICROSOFT_AUTH_CLIENTID="2cc60262-0026-48a5-ac2a-a088e9704f30"
window.REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL="https://desa.performance.40.121.134.234.nip.io/web-admision/"
window.REACT_APP_TIPO_ACCIDENTE_TRAYECTO = "https://desa.performance.40.121.134.234.nip.io/orquestador/api/trayecto/getTipoAccidente/"
window.REACT_APP_MEDIO_TRANSPORTE_TRAYECTO = "https://desa.performance.40.121.134.234.nip.io/orquestador/api/trayecto/getMediosTransporte/"
window.REACT_APP_PARTES_DEL_CUERPO = "https://desa.performance.40.121.134.234.nip.io/orquestador/api/trayecto/getPartesCuerpo/"