#!/bin/sh
if [ -z "${REACT_APP_ISAPRES:-}" ]; then
    REACT_APP_ISAPRES=undefined
else
    REACT_APP_ISAPRES=$(jq -n --arg REACT_APP_ISAPRES $REACT_APP_ISAPRES '$REACT_APP_ISAPRES')
fi

if [ -z "${REACT_APP_AFP:-}" ]; then
    REACT_APP_AFP=undefined
else
    REACT_APP_AFP=$(jq -n --arg REACT_APP_AFP $REACT_APP_AFP '$REACT_APP_AFP')
fi

if [ -z "${REACT_APP_NACIONALIDADES:-}" ]; then
    REACT_APP_NACIONALIDADES=undefined
else
    REACT_APP_NACIONALIDADES=$(jq -n --arg REACT_APP_NACIONALIDADES $REACT_APP_NACIONALIDADES '$REACT_APP_NACIONALIDADES')
fi

if [ -z "${REACT_APP_IDIOMAS:-}" ]; then
    REACT_APP_IDIOMAS=undefined
else
    REACT_APP_IDIOMAS=$(jq -n --arg REACT_APP_IDIOMAS $REACT_APP_IDIOMAS '$REACT_APP_IDIOMAS')
fi

if [ -z "${REACT_APP_PAISES:-}" ]; then
    REACT_APP_PAISES=undefined
else
    REACT_APP_PAISES=$(jq -n --arg REACT_APP_PAISES $REACT_APP_PAISES '$REACT_APP_PAISES')
fi

if [ -z "${REACT_APP_CATEGORIA_OCUPACIONAL:-}" ]; then
    REACT_APP_CATEGORIA_OCUPACIONAL=undefined
else
    REACT_APP_CATEGORIA_OCUPACIONAL=$(jq -n --arg REACT_APP_CATEGORIA_OCUPACIONAL $REACT_APP_CATEGORIA_OCUPACIONAL '$REACT_APP_CATEGORIA_OCUPACIONAL')
fi
 
if [ -z "${REACT_APP_TIPO_CONTRATO:-}" ]; then
    REACT_APP_TIPO_CONTRATO=undefined
else
    REACT_APP_TIPO_CONTRATO=$(jq -n --arg REACT_APP_TIPO_CONTRATO $REACT_APP_TIPO_CONTRATO '$REACT_APP_TIPO_CONTRATO')
fi

if [ -z "${REACT_APP_JORNADA_TRABAJO:-}" ]; then
    REACT_APP_JORNADA_TRABAJO=undefined
else
    REACT_APP_JORNADA_TRABAJO=$(jq -n --arg REACT_APP_JORNADA_TRABAJO $REACT_APP_JORNADA_TRABAJO '$REACT_APP_JORNADA_TRABAJO')
fi

if [ -z "${REACT_APP_TIPO_REMUNERACIONES:-}" ]; then
    REACT_APP_TIPO_REMUNERACIONES=undefined
else
    REACT_APP_TIPO_REMUNERACIONES=$(jq -n --arg REACT_APP_TIPO_REMUNERACIONES $REACT_APP_TIPO_REMUNERACIONES '$REACT_APP_TIPO_REMUNERACIONES')
fi

if [ -z "${REACT_APP_COMUNA:-}" ]; then
    REACT_APP_COMUNA=undefined
else
    REACT_APP_COMUNA=$(jq -n --arg REACT_APP_COMUNA $REACT_APP_COMUNA '$REACT_APP_COMUNA')
fi


if [ -z "${REACT_APP_SUCURSALES:-}" ]; then
    REACT_APP_SUCURSALES=undefined
else
    REACT_APP_SUCURSALES=$(jq -n --arg REACT_APP_SUCURSALES $REACT_APP_SUCURSALES '$REACT_APP_SUCURSALES')
fi

if [ -z "${REACT_APP_CENTROSACHS:-}" ]; then
    REACT_APP_CENTROSACHS=undefined
else
    REACT_APP_CENTROSACHS=$(jq -n --arg REACT_APP_CENTROSACHS $REACT_APP_CENTROSACHS '$REACT_APP_CENTROSACHS')
fi

if [ -z "${REACT_APP_PROFESION:-}" ]; then
    REACT_APP_PROFESION=undefined
else
    REACT_APP_PROFESION=$(jq -n --arg REACT_APP_PROFESION $REACT_APP_PROFESION '$REACT_APP_PROFESION')
fi

if [ -z "${REACT_APP_ALERTAS:-}" ]; then
    REACT_APP_ALERTAS=undefined
else
    REACT_APP_ALERTAS=$(jq -n --arg REACT_APP_ALERTAS $REACT_APP_ALERTAS '$REACT_APP_ALERTAS')
fi


if [ -z "${REACT_APP_RAZONSOCIAL:-}" ]; then
    REACT_APP_RAZONSOCIAL=undefined
else
    REACT_APP_RAZONSOCIAL=$(jq -n --arg REACT_APP_RAZONSOCIAL $REACT_APP_RAZONSOCIAL '$REACT_APP_RAZONSOCIAL')
fi

if [ -z "${REACT_APP_CENTER_USER:-}" ]; then
    REACT_APP_CENTER_USER=undefined
else
    REACT_APP_CENTER_USER=$(jq -n --arg REACT_APP_CENTER_USER $REACT_APP_CENTER_USER '$REACT_APP_CENTER_USER')
fi

if [ -z "${REACT_APP_LOG:-}" ]; then
    REACT_APP_LOG=undefined
else
    REACT_APP_LOG=$(jq -n --arg REACT_APP_LOG $REACT_APP_LOG '$REACT_APP_LOG')
fi

if [ -z "${REACT_APP_RAZON_SOCIAL_RUT:-}" ]; then
    REACT_APP_RAZON_SOCIAL_RUT=undefined
else
    REACT_APP_RAZON_SOCIAL_RUT=$(jq -n --arg REACT_APP_RAZON_SOCIAL_RUT $REACT_APP_RAZON_SOCIAL_RUT '$REACT_APP_RAZON_SOCIAL_RUT')
fi

if [ -z "${REACT_APP_VALIDAR_DATA_EMPRESA:-}" ]; then
    REACT_APP_VALIDAR_DATA_EMPRESA=undefined
else
    REACT_APP_VALIDAR_DATA_EMPRESA=$(jq -n --arg REACT_APP_VALIDAR_DATA_EMPRESA $REACT_APP_VALIDAR_DATA_EMPRESA '$REACT_APP_VALIDAR_DATA_EMPRESA')
fi

if [ -z "${REACT_APP_VALIDAR_DATA_PACIENTE:-}" ]; then
    REACT_APP_VALIDAR_DATA_PACIENTE=undefined
else
    REACT_APP_VALIDAR_DATA_PACIENTE=$(jq -n --arg REACT_APP_VALIDAR_DATA_PACIENTE $REACT_APP_VALIDAR_DATA_PACIENTE '$REACT_APP_VALIDAR_DATA_PACIENTE')
fi

if [ -z "${REACT_APP_INTEGRACION_SAP:-}" ]; then
    REACT_APP_INTEGRACION_SAP=undefined
else
    REACT_APP_INTEGRACION_SAP=$(jq -n --arg REACT_APP_INTEGRACION_SAP $REACT_APP_INTEGRACION_SAP '$REACT_APP_INTEGRACION_SAP')
fi

if [ -z "${REACT_APP_HOMOLOGACION:-}" ]; then
    REACT_APP_HOMOLOGACION=undefined
else
    REACT_APP_HOMOLOGACION=$(jq -n --arg REACT_APP_HOMOLOGACION $REACT_APP_HOMOLOGACION '$REACT_APP_HOMOLOGACION')
fi

if [ -z "${REACT_APP_GEO_AUTOCOMPLETE:-}" ]; then
    REACT_APP_GEO_AUTOCOMPLETE=undefined
else
    REACT_APP_GEO_AUTOCOMPLETE=$(jq -n --arg REACT_APP_GEO_AUTOCOMPLETE $REACT_APP_GEO_AUTOCOMPLETE '$REACT_APP_GEO_AUTOCOMPLETE')
fi

if [ -z "${REACT_APP_GEO_STATICMAP:-}" ]; then
    REACT_APP_GEO_STATICMAP=undefined
else
    REACT_APP_GEO_STATICMAP=$(jq -n --arg REACT_APP_GEO_STATICMAP $REACT_APP_GEO_STATICMAP '$REACT_APP_GEO_STATICMAP')
fi

if [ -z "${REACT_APP_GEO_LATLNG:-}" ]; then
    REACT_APP_GEO_LATLNG=undefined
else
    REACT_APP_GEO_LATLNG=$(jq -n --arg REACT_APP_GEO_LATLNG $REACT_APP_GEO_LATLNG '$REACT_APP_GEO_LATLNG')
fi

if [ -z "${REACT_APP_GEO_DIRECTION:-}" ]; then
    REACT_APP_GEO_DIRECTION=undefined
else
    REACT_APP_GEO_DIRECTION=$(jq -n --arg REACT_APP_GEO_DIRECTION $REACT_APP_GEO_DIRECTION '$REACT_APP_GEO_DIRECTION')
fi

if [ -z "${REACT_APP_MICROSOFT_AUTH_CLIENTID:-}" ]; then
    REACT_APP_MICROSOFT_AUTH_CLIENTID=undefined
else
    REACT_APP_MICROSOFT_AUTH_CLIENTID=$(jq -n --arg REACT_APP_MICROSOFT_AUTH_CLIENTID $REACT_APP_MICROSOFT_AUTH_CLIENTID '$REACT_APP_MICROSOFT_AUTH_CLIENTID')
fi

if [ -z "${REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL:-}" ]; then
    REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL=undefined
else
    REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL=$(jq -n --arg REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL $REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL '$REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL')
fi

if [ -z "${REACT_APP_TIPO_ACCIDENTE_TRAYECTO:-}" ]; then
    REACT_APP_TIPO_ACCIDENTE_TRAYECTO=undefined
else
    REACT_APP_TIPO_ACCIDENTE_TRAYECTO=$(jq -n --arg REACT_APP_TIPO_ACCIDENTE_TRAYECTO $REACT_APP_TIPO_ACCIDENTE_TRAYECTO '$REACT_APP_TIPO_ACCIDENTE_TRAYECTO')
fi

if [ -z "${REACT_APP_MEDIO_TRANSPORTE_TRAYECTO:-}" ]; then
    REACT_APP_MEDIO_TRANSPORTE_TRAYECTO=undefined
else
    REACT_APP_MEDIO_TRANSPORTE_TRAYECTO=$(jq -n --arg REACT_APP_MEDIO_TRANSPORTE_TRAYECTO $REACT_APP_MEDIO_TRANSPORTE_TRAYECTO '$REACT_APP_MEDIO_TRANSPORTE_TRAYECTO')
fi
 
cat <<EOF
window.REACT_APP_ISAPRES=$REACT_APP_ISAPRES
window.REACT_APP_AFP=$REACT_APP_AFP
window.REACT_APP_NACIONALIDADES=$REACT_APP_NACIONALIDADES
window.REACT_APP_IDIOMAS=$REACT_APP_IDIOMAS
window.REACT_APP_PAISES=$REACT_APP_PAISES
window.REACT_APP_CATEGORIA_OCUPACIONAL=$REACT_APP_CATEGORIA_OCUPACIONAL
window.REACT_APP_TIPO_CONTRATO=$REACT_APP_TIPO_CONTRATO
window.REACT_APP_JORNADA_TRABAJO=$REACT_APP_JORNADA_TRABAJO
window.REACT_APP_TIPO_REMUNERACIONES=$REACT_APP_TIPO_REMUNERACIONES
window.REACT_APP_COMUNA=$REACT_APP_COMUNA
window.REACT_APP_SUCURSALES=$REACT_APP_SUCURSALES
window.REACT_APP_CENTROSACHS=$REACT_APP_CENTROSACHS
window.REACT_APP_PROFESION=$REACT_APP_PROFESION
window.REACT_APP_ALERTAS=$REACT_APP_ALERTAS
window.REACT_APP_RAZONSOCIAL=$REACT_APP_RAZONSOCIAL
window.REACT_APP_CENTER_USER=$REACT_APP_CENTER_USER
window.REACT_APP_LOG=$REACT_APP_LOG
window.REACT_APP_RAZON_SOCIAL_RUT=$REACT_APP_RAZON_SOCIAL_RUT
window.REACT_APP_VALIDAR_DATA_EMPRESA=$REACT_APP_VALIDAR_DATA_EMPRESA
window.REACT_APP_VALIDAR_DATA_PACIENTE=$REACT_APP_VALIDAR_DATA_PACIENTE
window.REACT_APP_INTEGRACION_SAP=$REACT_APP_INTEGRACION_SAP
window.REACT_APP_HOMOLOGACION=$REACT_APP_HOMOLOGACION
window.REACT_APP_GEO_AUTOCOMPLETE=$REACT_APP_GEO_AUTOCOMPLETE
window.REACT_APP_GEO_STATICMAP=$REACT_APP_GEO_STATICMAP
window.REACT_APP_GEO_LATLNG=$REACT_APP_GEO_LATLNG
window.REACT_APP_GEO_DIRECTION=$REACT_APP_GEO_DIRECTION
window.REACT_APP_MICROSOFT_AUTH_CLIENTID=$REACT_APP_MICROSOFT_AUTH_CLIENTID
window.REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL=$REACT_APP_MICROSOFT_AUTH_POSTLOGOUTREDIRECTURL
window.REACT_APP_TIPO_ACCIDENTE_TRAYECTO=$REACT_APP_TIPO_ACCIDENTE_TRAYECTO
window.REACT_APP_MEDIO_TRANSPORTE_TRAYECTO=$REACT_APP_MEDIO_TRANSPORTE_TRAYECTO
EOF