apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-front-admision-ingress2
  annotations:
       kubernetes.io/ingress.class: nginx
       cert-manager.io/cluster-issuer: admision-cert

spec:
  tls:
    - hosts:
      - desa.salud.achs.cl 
      secretName: admision-web-cert
  rules:
  - host: desa.salud.achs.cl
    http:
      paths:
      - backend:
          serviceName: web-front-admision-service
          servicePort: 80
        path: /admision         