apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-front-admision-ingress
  annotations:
       kubernetes.io/ingress.class: nginx
       cert-manager.io/cluster-issuer: letsencrypt
       nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  tls:
    - hosts:
      - desa.salud.achs.cl
      secretName: admision-web-cert
  rules:
  - host: desa.salud.achs.cl 
    http:
      paths:
      - path: /web-admision(/?.*)
        backend:
          serviceName: web-front-admision-service
          servicePort: 80
      - path: /orquestador/(.*)
        backend:
          serviceName: api-orquestador-service
          servicePort: 80       