apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front-admision-sprintName
spec:
  selector:
    matchLabels:
      app: web-front-admision-sprintName
  template:
    metadata:
      labels:
        app: web-front-admision-sprintName
    spec:
      containers:
      - name: web-front-admision-sprintName
        image: imagen          
        imagePullPolicy: Always
        env:
          - name: PUBLIC_URL
            value: /web-admision     
          - name: ENTORNO
            value: ParallelDesarrollo
          - name: nombreSprint
            value: sprintName

        ports:
        - containerPort: 80
        resources:
          requests: 
            cpu: 50m
            memory: 64Mi
          limits: 
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: regcred-crdesacontainer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-front-admision-sprintName
spec:
  maxReplicas: 10
  minReplicas: 2 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-front-admision-sprintName
  targetCPUUtilizationPercentage: 50