import { makeStyles } from "@material-ui/core/styles";

export const siniestroStyle = makeStyles((theme) => ({
  root: {
    width: "22.5em",
    height: "40em",
    margin: "0px",
    border: "0px",
    padding: "0px",
  },
  item1: {
    height: "0.9375em",
    margin: "0px",
    border: "0px",
    padding: "0px",
  },
  item1Text: {
    fontFamily: "sfUiDisplayCufonfonts",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "0.75em",
    lineHeight: "0.875em",
  },
  item2: {
    height: "1.16375em",
    margin: "0px",
    border: "0px",
    padding: "0px",
  },
  item3: {
    width: "20%",
    height: "1,0475em",
    margin: "0px",
    border: "0px",
    float: "left",
  },
  item4: {
    paddingTop: "0.5em",
    padding: "0",
    width: "17.75em",
    height: "1,0475em",
    margin: "0px",
    border: "0px",
    float: "left",
  },
  item5: {
    float: "none",
    clear: "both",
    margin: "0px",
    border: "0px",
  },
  item6: {
    height: "3.75em",
    margin: "0px",
    border: "0px",
    padding: "0px",
    paddingTop: "2em",
  },
  item7: {
    height: "3.5625em",
    margin: "0px",
    border: "0px",
    padding: "0px",
  },
  item8: {
    height: "5em",
    margin: "0px",
    border: "0px",
    padding: "0px",
    textAlign: "left",
    justifyContent: "flex-start",
  },
  button: {
    width: "100%",
    height: "100%",
    background: "#007A33",
    boxShadow: "0.125em 0.125em 0.375em rgba(203, 203, 203, 0.4)",
    borderRadius: "0.25em",
    fontFamily: "Catamaran",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "1em",
    lineHeight: "1.125em",
    color: "#FFFFFF",
    textTransform: "capitalize",
    textAlign: "left",
    justifyContent: "flex-start",
  },
  item9: {
    height: "2.5625em",
    margin: "0px",
    border: "0px",
    padding: "0px",
  },
  img: {
    width: "3em",
    height: "3em",
  },
  mobileLabel: {
    fontFamily: "Catamaran",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "12px",
    lineHeight: "14px",
    letterSpacing: "0.3em",
    textTransform: "uppercase",
    color: "#787878",
  },
  mobileCaption: {
    fontFamily: "Catamaran",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "13px",
    lineHeight: "16px",
    color: "#787878",
  },
}));
