export const SET_STEP = 'SET_STEP'
export const UPDATE_FORM = 'UPDATE_FORM'


export const SEARCH_ISAPRES_INIT = 'SEARCH_ISAPRES_INIT'
export const SEARCH_ISAPRES_SUCCESS = 'SEARCH_ISAPRES_SUCCESS'
export const SEARCH_ISAPRES_FAILURE = 'SEARCH_ISAPRES_FAILURE'
export const SEND_ISAPRES = 'SEND_ISAPRES'

export const SEND_TESTIGO = 'SEND_TESTIGO'

export const SEND_RESPONSABLE = 'SEND_RESPONSABLE'