export const SET_STEP = "SET_STEP";
export const UPDATE_FORM = "UPDATE_FORM";
export const LOAD_STATE_SESSIONSTORAGE = "LOAD_STATE_SESSIONSTORAGE";

export const SEARCH_ISAPRES_INIT = "SEARCH_ISAPRES_INIT";
export const SEARCH_ISAPRES_SUCCESS = "SEARCH_ISAPRES_SUCCESS";
export const SEARCH_ISAPRES_FAILURE = "SEARCH_ISAPRES_FAILURE";
export const SEND_ISAPRES = "SEND_ISAPRES";

export const SEND_TESTIGO = "SEND_TESTIGO";

export const SEND_RESPONSABLE = "SEND_RESPONSABLE";

export const SEND_CENTROACHS = "SEND_CENTROACHS";
export const CLEAR_STATE = "CLEAR_STATE";


export const DATE_EMPRESA_SUCCESS = "DATE_EMPRESA_SUCCESS";
export const DATE_EMPRESA_FAILURE = "DATE_EMPRESA_FAILURE";

export const RESPONSE_SUCCESS = "RESPONSE_SUCCESS";
export const RESPONSE_ERROR = "RESPONSE_ERROR";
