export const SET_STEP = 'SET_STEP'
export const UPDATE_FORM = 'UPDATE_FORM'


export const SEARCH_ISAPRES = 'SEARCH_ISAPRES'
export const SEARCH_ISAPRES_SUCCESS = 'SEARCH_ISAPRES_SUCCESS'
export const SEARCH_ISAPRES_ERROR = 'SEARCH_ISAPRES_ERROR'
export const SEND_ISAPRES = 'SEND_ISAPRES'