export const GET_CATEGORIAOCUPACIONAL_INIT = "GET_CATEGORIAOCUPACIONAL_INIT";
export const GET_CATEGORIAOCUPACIONAL_SUCCESS =
  "GET_CATEGORIAOCUPACIONAL_SUCCESS";
export const GET_CATEGORIAOCUPACIONAL_FAILURE =
  "GET_CATEGORIAOCUPACIONAL_FAILURE";
