export const SET_FECHA_HORA_SINIESTRO_INIT = "SET_FECHA_HORA_SINIESTRO_INIT";
export const SET_FECHA_HORA_SINIESTRO_SUCCESS =
  "SET_FECHA_HORA_SINIESTRO_SUCCESS";
export const SET_FECHA_HORA_SINIESTRO_FAILURE =
  "SET_FECHA_HORA_SINIESTRO_FAILURE";
