export const POST_LOG_INIT = "POST_LOG_INIT";
export const POST_LOG_SUCCESS = "POST_LOG_SUCCESS";
export const POST_LOG_FAILURE = "POST_LOG_FAILURE";
export const LOAD_LOG_STATE_SESSIONSTORAGE = "LOAD_LOG_STATE_SESSIONSTORAGE";
