export const POST_LOG_INIT = "POST_LOG_INIT";
export const POST_LOG_SUCCESS = "POST_LOG_SUCCESS";
export const POST_LOG_FAILURE = "POST_LOG_FAILURE";
export const POST_LOG_INIT_STEP = "POST_LOG_INIT_STEP";
export const POST_LOG_SUCCESS_STEP = "POST_LOG_SUCCESS_STEP";
export const POST_LOG_FAILURE_STEP = "POST_LOG_FAILURE_STEP";
export const LOAD_LOG_STATE_SESSIONSTORAGE = "LOAD_LOG_STATE_SESSIONSTORAGE";
