export const GET_SUCURSALES_EMPRESA_SINIESTRO_INIT =
  "GET_SUCURSALES_EMPRESA_SINIESTRO_INIT";
export const GET_SUCURSALES_EMPRESA_SINIESTRO_SUCCESS =
  "GET_SUCURSALES_EMPRESA_SINIESTRO_SUCCESS";
export const GET_SUCURSALES_EMPRESA_SINIESTRO_FAILURE =
  "GET_SUCURSALES_EMPRESA_SINIESTRO_FAILURE";

export const SET_SUCURSALES_EMPRESA_SINIESTRO_INIT =
  "SET_SUCURSALES_EMPRESA_SINIESTRO_INIT";
export const SET_SUCURSALES_EMPRESA_SINIESTRO_SUCCESS =
  "SET_SUCURSALES_EMPRESA_SINIESTRO_SUCCESS";
export const SET_SUCURSALES_EMPRESA_SINIESTRO_FAILURE =
  "SET_SUCURSALES_EMPRESA_SINIESTRO_FAILURE";
