export const GET_JORNADA_LABORAL_INIT = "GET_JORNADA_LABORAL_INIT";
export const GET_JORNADA_LABORAL_SUCCESS = "GET_JORNADA_LABORAL_SUCCESS";
export const GET_JORNADA_LABORAL_FAILURE = "GET_JORNADA_LABORAL_FAILURE";
