export const GET_TRAYECTO_INIT = "GET_TRAYECTO_INIT";
export const GET_TRAYECTO_SUCCESS = "GET_TRAYECTO_SUCCESS";
export const GET_TRAYECTO_FAILURE = "GET_TRAYECTO_FAILURE";

export const GET_TRAYECTO_MEDIOTRANSPORTE_INIT = "GET_TRAYECTO_MEDIOTRANSPORTE_INIT";
export const GET_TRAYECTO_MEDIOTRANSPORTE_SUCCESS = "GET_TRAYECTO_MEDIOTRANSPORTE_SUCCESS";
export const GET_TRAYECTO_MEDIOTRANSPORTE_FAILURE = "GET_TRAYECTO_MEDIOTRANSPORTE_FAILURE";
