apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-qa-front-admision-ingress
  annotations:
       kubernetes.io/ingress.class: nginx
       cert-manager.io/cluster-issuer: letsencrypt
       nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  tls:
    - hosts:
      - qa.salud.achs.cl
      secretName: admision-web-cert
  rules:
  - host: qa.salud.achs.cl
    http:
      paths:
      - path: /web-admision(/?.*)
        backend:
          serviceName: web-qa-front-admision-service
          servicePort: 80
      - path: /web-firmadigital(/?.*)
        backend:
          serviceName: web-qa-front-firmadigital-service
          servicePort: 80
      - path: /web-firmadigital-totem(/?.*)
        backend:
          serviceName: web-qa-front-firmadigital-service-totem-sprint10
          servicePort: 80             
      - path: /web-digitalizador-documentos(/?.*)
        backend:
          serviceName: web-qa-front-digitalizaciondocumentos-service
          servicePort: 80   
       