apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: admision-cert
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sadiazg@achs.cl # IMPORTANT: Replace with a valid email from your organization
    privateKeySecretRef:
      name: admision-cert
    solvers:
    - http01:
        ingress:
          class: nginx