apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-qa-front-admision
spec:
  selector:
    matchLabels:
      app: web-qa-front-admision
  template:
    metadata:
      labels:
        app: web-qa-front-admision
    spec:
      containers:
      - name: web-qa-front-admision
        image: imagen         
        imagePullPolicy: Always
        env:
          - name: PUBLIC_URL
            value: /web-admision     
          - name: ENTORNO
            value: qa
        ports:
        - containerPort: 80
        resources:
          requests: 
            cpu: 100m
            memory: 64Mi
          limits: 
            cpu: 200m
            memory: 128Mi
      imagePullSecrets:
      - name: regcred-crdesacontainer 