apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-qa-front-admision-ingress-sprint10
  annotations:
       kubernetes.io/ingress.class: nginx
       cert-manager.io/cluster-issuer: letsencrypt
       nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  tls:
    - hosts:
      - qa.sprint10.52.149.214.89.nip.io 
      secretName: admision-web-cert
  rules:
  - host: qa.sprint10.52.149.214.89.nip.io
    http:
      paths:
      - path: /web-admision(/?.*)
        backend:
          serviceName: web-qa-front-admision-service-sprint10
          servicePort: 80
      - path: /web-firmadigital(/?.*)
        backend:
          serviceName: web-qa-front-firmadigital-service-sprint10
          servicePort: 80   
      - path: /web-digitalizador-documentos(/?.*)
        backend:
          serviceName: web-qa-front-digitalizaciondocumentos-service-sprint10
          servicePort: 80   
      - path: /orquestador/(.*)
        backend:
          serviceName: api-qa-orquestador-service-sprint10
          servicePort: 80
       