apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-stg-front-admision
spec:
  selector:
    matchLabels:
      app: web-stg-front-admision
  template:
    metadata:
      labels:
        app: web-stg-front-admision
    spec:
      containers:
      - name: web-stg-front-admision
        image: imagen         
        imagePullPolicy: Always
        env:
          - name: PUBLIC_URL
            value: /web-admision     
          - name: ENTORNO
            value: staging          
        ports:
        - containerPort: 80
        resources:
          requests: 
            cpu: 25m
            memory: 32Mi
          limits: 
            cpu: 50m
            memory: 64Mi
      imagePullSecrets:
      - name: regcred-crdesacontainer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-stg-front-admision
spec:
  maxReplicas: 10
  minReplicas: 2 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-stg-front-admision
  targetCPUUtilizationPercentage: 50